env:  
    node: true
extends:  
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: 9
    project: ./tsconfig.json
plugins:
- '@typescript-eslint'
